[workspace]
members = ["uniclass", "uniclass-data", "uniclass-gen-ts"]
resolver = "2"

[workspace.package]
version = "0.3.59"
authors = ["Jake O'Shannessy <joshannessy@threadway.com>"]
edition = "2021"
rust-version = "1.80"
